server:
  port: 1004
spring:
  application:
    name: camunda-service
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/camunda?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
      username: root
      password: 123456
      driverClassName: com.mysql.cj.jdbc.Driver
      initialSize: 5  #\u521D\u59CB\u5EFA\u7ACB\u8FDE\u63A5\u6570\u91CF
      minIdle: 5  #\u6700\u5C0F\u8FDE\u63A5\u6570\u91CF
      maxActive: 20 #\u6700\u5927\u8FDE\u63A5\u6570\u91CF
      maxWait: 10000 #\u83B7\u53D6\u8FDE\u63A5\u6700\u5927\u7B49\u5F85\u65F6\u95F4\uFF0C\u6BEB\u79D2
      testOnBorrow: true #\u7533\u8BF7\u8FDE\u63A5\u65F6\u68C0\u6D4B\u8FDE\u63A5\u662F\u5426\u6709\u6548
      testOnReturn: false #\u5F52\u8FD8\u8FDE\u63A5\u65F6\u68C0\u6D4B\u8FDE\u63A5\u662F\u5426\u6709\u6548
      timeBetweenEvictionRunsMillis: 60000 #\u914D\u7F6E\u95F4\u9694\u68C0\u6D4B\u8FDE\u63A5\u662F\u5426\u6709\u6548\u7684\u65F6\u95F4\uFF08\u5355\u4F4D\u662F\u6BEB\u79D2\uFF09
      minEvictableIdleTimeMillis: 300000 #\u6700\u5C0F\u7A7A\u95F2\u65F6\u95F4
camunda:
  bpm:
    #\u914D\u7F6E\u8D26\u6237\u5BC6\u7801\u6765\u8BBF\u95EECamunda\u81EA\u5E26\u7684\u7BA1\u7406\u754C\u9762
    admin-user:
      id: admin
      password: admin
      first-name: admin
    filter:
      create: All tasks
    #\u6307\u5B9A\u6570\u636E\u5E93\u7C7B\u578B
    database:
      type: mysql
    #\u7981\u6B62\u81EA\u52A8\u90E8\u7F72resources\u4E0B\u9762\u7684bpmn\u6587\u4EF6
    auto-deployment-enabled: false
    #\u7981\u6B62index\u8DF3\u8F6C\u5230Camunda\u81EA\u5E26\u7684\u7BA1\u7406\u754C\u9762\uFF0C\u9ED8\u8BA4true
    webapp:
      index-redirect-enabled: true
