server:
  port: 18081 # 服务端口号
spring:
  application:
    name: nacos-discovery1 # 服务名称
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 # Nacos服务地址
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080 # Sentinel控制台地址
    stream:
      # RocketMQ 通用配置
      rocketmq:
        binder:
          name-server: 127.0.0.1:9876 # 客户端接入点，必填  rocketMQ的连接地址，binder高度抽象
          group: rocketmq-group # 不加，会报错：Property 'group' is required - producerGroup
      # bindings 具体生产消息、消费消息的桥梁
      bindings:
        output1:
          destination: test-topic1
          content-type: text/plain
        output2:
          destination: test-topic2
          content-type: text/plain
logging:
  level:
    com.alibaba.cloud.stream.binder.rocketmq: info
# 启动所有监控点（http://localhost:18081/actuator/health）
management:
  endpoints:
    web:
      exposure:
        include: '*'